package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysAnnounce;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAnnounce extends BaseSysAnnounce<SysAnnounce> {
	public static final SysAnnounce dao = new SysAnnounce().dao();
}
