package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	public static final SysDict dao = new SysDict().dao();
}
