package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperLog extends BaseSysOperLog<SysOperLog> {
	public static final SysOperLog dao = new SysOperLog().dao();
}
