package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysParam extends BaseSysParam<SysParam> {
	public static final SysParam dao = new SysParam().dao();
}
