package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	public static final SysRoleMenu dao = new SysRoleMenu().dao();
}
