package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();
}
