package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSequence extends BaseSysSequence<SysSequence> {
	public static final SysSequence dao = new SysSequence().dao();
}
