package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysTask extends BaseSysTask<SysTask> {
	public static final SysTask dao = new SysTask().dao();
}
