package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysArea<M extends BaseSysArea<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public M setShortname(String shortname) {
		set("shortname", shortname);
		return (M)this;
	}

	public String getShortname() {
		return getStr("shortname");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setMergerName(String mergerName) {
		set("merger_name", mergerName);
		return (M)this;
	}

	public String getMergerName() {
		return getStr("merger_name");
	}

	public M setLevel(Boolean level) {
		set("level", level);
		return (M)this;
	}

	public Boolean getLevel() {
		return get("level");
	}

	public M setPinyin(String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}

	public String getPinyin() {
		return getStr("pinyin");
	}

	public M setCode(String code) {
		set("code", code);
		return (M)this;
	}

	public String getCode() {
		return getStr("code");
	}

	public M setZipCode(String zipCode) {
		set("zip_code", zipCode);
		return (M)this;
	}

	public String getZipCode() {
		return getStr("zip_code");
	}

	public M setFirst(String first) {
		set("first", first);
		return (M)this;
	}

	public String getFirst() {
		return getStr("first");
	}

	public M setLng(String lng) {
		set("lng", lng);
		return (M)this;
	}

	public String getLng() {
		return getStr("lng");
	}

	public M setLat(String lat) {
		set("lat", lat);
		return (M)this;
	}

	public String getLat() {
		return getStr("lat");
	}

}
