package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("user_id");
	}

	public M setLoginName(String loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public String getLoginName() {
		return getStr("login_name");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("user_name");
	}

	public M setUserPassword(String userPassword) {
		set("user_password", userPassword);
		return (M)this;
	}

	public String getUserPassword() {
		return getStr("user_password");
	}

	public M setUserSex(String userSex) {
		set("user_sex", userSex);
		return (M)this;
	}

	public String getUserSex() {
		return getStr("user_sex");
	}

	public M setUserBirthday(java.util.Date userBirthday) {
		set("user_birthday", userBirthday);
		return (M)this;
	}

	public java.util.Date getUserBirthday() {
		return get("user_birthday");
	}

	public M setUserMobile(String userMobile) {
		set("user_mobile", userMobile);
		return (M)this;
	}

	public String getUserMobile() {
		return getStr("user_mobile");
	}

	public M setUserEmail(String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}

	public String getUserEmail() {
		return getStr("user_email");
	}

	public M setFaceImageUrl(String faceImageUrl) {
		set("face_image_url", faceImageUrl);
		return (M)this;
	}

	public String getFaceImageUrl() {
		return getStr("face_image_url");
	}

	public M setDepartmentId(Integer departmentId) {
		set("department_id", departmentId);
		return (M)this;
	}

	public Integer getDepartmentId() {
		return getInt("department_id");
	}

	public M setDuties(String duties) {
		set("duties", duties);
		return (M)this;
	}

	public String getDuties() {
		return getStr("duties");
	}

	public M setSort(String sort) {
		set("sort", sort);
		return (M)this;
	}

	public String getSort() {
		return getStr("sort");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
