package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setParentId(Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public Integer getParentId() {
		return getInt("parent_id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setUrl(String url) {
		set("url", url);
		return (M)this;
	}

	public String getUrl() {
		return getStr("url");
	}

	public M setPerms(String perms) {
		set("perms", perms);
		return (M)this;
	}

	public String getPerms() {
		return getStr("perms");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}

	public String getType() {
		return getStr("type");
	}

	public M setIcon(String icon) {
		set("icon", icon);
		return (M)this;
	}

	public String getIcon() {
		return getStr("icon");
	}

	public M setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public Integer getOrderNum() {
		return getInt("order_num");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
