package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysSms<M extends BaseSysSms<M>> extends Model<M> implements IBean {

	public M setSmsNo(String smsNo) {
		set("sms_no", smsNo);
		return (M)this;
	}

	public String getSmsNo() {
		return getStr("sms_no");
	}

	public M setSmsType(String smsType) {
		set("sms_type", smsType);
		return (M)this;
	}

	public String getSmsType() {
		return getStr("sms_type");
	}

	public M setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
		return (M)this;
	}

	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public M setSendContent(String sendContent) {
		set("send_content", sendContent);
		return (M)this;
	}

	public String getSendContent() {
		return getStr("send_content");
	}

	public M setReceiver(String receiver) {
		set("receiver", receiver);
		return (M)this;
	}

	public String getReceiver() {
		return getStr("receiver");
	}

	public M setReceiverPhone(String receiverPhone) {
		set("receiver_phone", receiverPhone);
		return (M)this;
	}

	public String getReceiverPhone() {
		return getStr("receiver_phone");
	}

	public M setSendStatus(String sendStatus) {
		set("send_status", sendStatus);
		return (M)this;
	}

	public String getSendStatus() {
		return getStr("send_status");
	}

	public M setValidateStatus(String validateStatus) {
		set("validate_status", validateStatus);
		return (M)this;
	}

	public String getValidateStatus() {
		return getStr("validate_status");
	}

	public M setEmployStatus(String employStatus) {
		set("employ_status", employStatus);
		return (M)this;
	}

	public String getEmployStatus() {
		return getStr("employ_status");
	}

	public M setExpireTime(String expireTime) {
		set("expire_time", expireTime);
		return (M)this;
	}

	public String getExpireTime() {
		return getStr("expire_time");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
