package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysHomeModule<M extends BaseSysHomeModule<M>> extends Model<M> implements IBean {

	public M setModuleNo(Integer moduleNo) {
		set("module_no", moduleNo);
		return (M)this;
	}

	public Integer getModuleNo() {
		return getInt("module_no");
	}

	public M setModuleName(String moduleName) {
		set("module_name", moduleName);
		return (M)this;
	}

	public String getModuleName() {
		return getStr("module_name");
	}

	public M setModuleImage(String moduleImage) {
		set("module_image", moduleImage);
		return (M)this;
	}

	public String getModuleImage() {
		return getStr("module_image");
	}

	public M setModuleOrder(String moduleOrder) {
		set("module_order", moduleOrder);
		return (M)this;
	}

	public String getModuleOrder() {
		return getStr("module_order");
	}

	public M setModuleLike(String moduleLike) {
		set("module_like", moduleLike);
		return (M)this;
	}

	public String getModuleLike() {
		return getStr("module_like");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
