package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRoleMenu<M extends BaseSysRoleMenu<M>> extends Model<M> implements IBean {

	public M setRoleMenuId(Integer roleMenuId) {
		set("role_menu_id", roleMenuId);
		return (M)this;
	}

	public Integer getRoleMenuId() {
		return getInt("role_menu_id");
	}

	public M setRoleId(Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Integer getRoleId() {
		return getInt("role_id");
	}

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

}
