package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	public M setRoleId(Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Integer getRoleId() {
		return getInt("role_id");
	}

	public M setRoleName(String roleName) {
		set("role_name", roleName);
		return (M)this;
	}

	public String getRoleName() {
		return getStr("role_name");
	}

	public M setRoleDesc(String roleDesc) {
		set("role_desc", roleDesc);
		return (M)this;
	}

	public String getRoleDesc() {
		return getStr("role_desc");
	}

	public M setRoleType(String roleType) {
		set("role_type", roleType);
		return (M)this;
	}

	public String getRoleType() {
		return getStr("role_type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
