package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUserRole<M extends BaseSysUserRole<M>> extends Model<M> implements IBean {

	public M setUserRoleId(Integer userRoleId) {
		set("user_role_id", userRoleId);
		return (M)this;
	}

	public Integer getUserRoleId() {
		return getInt("user_role_id");
	}

	public M setRoleId(Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Integer getRoleId() {
		return getInt("role_id");
	}

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

}
