package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	public M setDictId(Integer dictId) {
		set("dict_id", dictId);
		return (M)this;
	}

	public Integer getDictId() {
		return getInt("dict_id");
	}

	public M setDictName(String dictName) {
		set("dict_name", dictName);
		return (M)this;
	}

	public String getDictName() {
		return getStr("dict_name");
	}

	public M setDictValue(String dictValue) {
		set("dict_value", dictValue);
		return (M)this;
	}

	public String getDictValue() {
		return getStr("dict_value");
	}

	public M setDictDesc(String dictDesc) {
		set("dict_desc", dictDesc);
		return (M)this;
	}

	public String getDictDesc() {
		return getStr("dict_desc");
	}

	public M setDictGroup(String dictGroup) {
		set("dict_group", dictGroup);
		return (M)this;
	}

	public String getDictGroup() {
		return getStr("dict_group");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

}
