package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysTask<M extends BaseSysTask<M>> extends Model<M> implements IBean {

	public M setJobId(Long JobId) {
		set("job_id", JobId);
		return (M)this;
	}

	public Long getJobId() {
		return getLong("job_id");
	}

	public M setClassPath(String classPath) {
		set("class_path", classPath);
		return (M)this;
	}

	public String getClassPath() {
		return getStr("class_path");
	}

	public M setBeanName(String beanName) {
		set("bean_name", beanName);
		return (M)this;
	}

	public String getBeanName() {
		return getStr("bean_name");
	}

	public M setJobDesc(String jobDesc) {
		set("job_desc", jobDesc);
		return (M)this;
	}

	public String getJobDesc() {
		return getStr("job_desc");
	}

	public M setParams(String params) {
		set("params", params);
		return (M)this;
	}

	public String getParams() {
		return getStr("params");
	}

	public M setCronExpression(String cronExpression) {
		set("cron_expression", cronExpression);
		return (M)this;
	}

	public String getCronExpression() {
		return getStr("cron_expression");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
