package com.ofsoft.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOperLog<M extends BaseSysOperLog<M>> extends Model<M> implements IBean {

	public M setLogid(Integer logid) {
		set("logid", logid);
		return (M)this;
	}

	public Integer getLogid() {
		return getInt("logid");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("user_name");
	}

	public M setFunctionName(String functionName) {
		set("function_name", functionName);
		return (M)this;
	}

	public String getFunctionName() {
		return getStr("function_name");
	}

	public M setBusinessCode(String businessCode) {
		set("business_code", businessCode);
		return (M)this;
	}

	public String getBusinessCode() {
		return getStr("business_code");
	}

	public M setUserId(String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public String getUserId() {
		return getStr("user_id");
	}

	public M setOperType(String operType) {
		set("oper_type", operType);
		return (M)this;
	}

	public String getOperType() {
		return getStr("oper_type");
	}

	public M setOperTime(java.util.Date operTime) {
		set("oper_time", operTime);
		return (M)this;
	}

	public java.util.Date getOperTime() {
		return get("oper_time");
	}

	public M setOperDesc(String operDesc) {
		set("oper_desc", operDesc);
		return (M)this;
	}

	public String getOperDesc() {
		return getStr("oper_desc");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
