#namespace("system.user")
	#include("system/user.sql")
#end

#namespace("system.role")
	#include("system/role.sql")
#end

#namespace("system.announce")
	#include("system/announce.sql")
#end
#namespace("system.menu")
	#include("system/menu.sql")
#end
#namespace("system.dict")
	#include("system/dict.sql")
#end
#namespace("system.param")
	#include("system/param.sql")
#end

#namespace("system.generate")
	#include("system/generate.sql")
#end
#namespace("system.task")
	#include("system/task.sql")
#end

#namespace("system.log")
	#include("system/log.sql")
#end

#namespace("weixin.auto")
	#include("weixin/auto.sql")
#end
#namespace("weixin.menu")
	#include("weixin/menu.sql")
#end
#namespace("weixin.reply")
	#include("weixin/reply.sql")
#end
#namespace("cms.link")
	#include("cms/link.sql")
#end
#namespace("cms.comment")
	#include("cms/comment.sql")
#end
#namespace("cms.column")
	#include("cms/column.sql")
#end
#namespace("cms.ad")
	#include("cms/ad.sql")
#end
#namespace("cms.site")
	#include("cms/site.sql")
#end
#namespace("cms.announce")
	#include("cms/announce.sql")
#end#namespace("cms.content")
	#include("cms/content.sql")
#end
#namespace("cms.form")
	#include("cms/form.sql")
#end
#namespace("cms.field")
	#include("cms/field.sql")
#end
#namespace("cms.recover")
	#include("cms/recover.sql")
#end
#namespace("cms.bbs")
	#include("cms/bbs.sql")
#end
#namespace("cms.topic")
	#include("cms/topic.sql")
#end
#namespace("cms.single")
	#include("cms/single.sql")
#end
#namespace("cms.count")
	#include("cms/count.sql")
#end